FROM node:20-alpine

WORKDIR /app

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
  && apk add --no-cache font-wqy-zenhei

COPY package*.json ./
RUN npm ci --omit=dev

EXPOSE 5174
